#!/bin/sh

# Hunchentoot daemon

. /var/lib/hunchentoot/htoot.conf

export SBCL_HOME=${SBCL_HOME:-'/usr/local/lib/sbcl'}
export LC_CTYPE="en_US.UTF-8"
export HOME=$HT_PREFIX
export HT_LOG HT_CORE

SBCL=${SBCL:-'/usr/local/bin/sbcl'}
DTTY=${DTTY:-'/usr/local/bin/detachtty'}
ATTY=${ATTY:-'/usr/local/bin/attachtty'}

case "$1" in
    start)
	if [ ! -f $HT_CORE ] ; then
	    $SBCL --script $HT_CORESRC
	    chown "${HT_USR}:${HT_GRP}" $HT_CORE
	    chmod 400 $HT_CORE
	fi

	$DTTY \
	    --dribble-file $HT_DRIBBLE \
	    --log-file $HT_DTTYLOG \
	    --pid-file $HT_PIDFILE \
	    $HT_SOCK \
	    $SBCL --core $HT_CORE --load $HT_STARTUP
	;;
    swank)
	$ATTY $HT_SOCK '(start-swank)'
	;;
    attach)
	$ATTY $HT_SOCK
	;;
    log)
	tail -f $HT_LOG
	;;
    stop)
	kill `cat $HT_PIDFILE` 2>/dev/null
	rm -f $HT_SOCK $HT_DRIBBLE $HT_DTTYLOG
	;;
    *)
	echo "usage: `basename $0` {start|stop|swank|log|attach}" >&2
	exit 1
	;;
esac

exit 0
