#!/bin/sh

# PROVIDE: hunchentoot
# REQUIRE: LOGIN httpd
# KEYWORD: shutdown

. /etc/rc.subr
. /var/lib/hunchentoot/htoot.conf

name="hunchentoot"
rcvar=`set_rcvar`

start_cmd="htoot_exec $HTOOTD start"
stop_cmd="htoot_exec $HTOOTD stop"
attach_cmd="htoot_exec $HTOOTD attach"
extra_commands="attach"

htoot_exec()
{
    su -m $HT_USR -c "$*"
}

required_files="/var/lib/hunchentoot/htoot.conf"

load_rc_config $name
run_rc_command "$1"
